language: node_js
node_js:
  - "7"
sudo: false
dist: trusty
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install libstdc++-4.9-dev -y
env:
  - TASK=test
  - TASK=srcclr
  - TASK=test:integration
matrix:
  fast_finish: true
  allow_failures:
    - TASK=test:integration
script:
  - |
    if [[ "$TASK" == "srcclr" ]]
    then
        echo "Starting Source clear ..."
        curl -sSL https://download.sourceclear.com/ci.sh | bash
    else
        echo "Running tests"
        yarn run $TASK
    fi
cache: yarn
branches:
  only: [master]
